// Bundles the transport shim into a single dependency-free IIFE that
// src-tauri/src/shim.rs embeds with include_str! and hands to a Tauri plugin's
// js_init_script. Left unminified: when something misbehaves in the packaged
// app, this is the file you read in the devtools.
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { build } from 'esbuild'

const here = dirname(fileURLToPath(import.meta.url))
const outfile = resolve(here, 'src-tauri/shim.js')

await build({
  entryPoints: [resolve(here, 'shim/entry.ts')],
  outfile,
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['es2022'],
  minify: false,
  legalComments: 'none',
  banner: {
    js: '/* Generated by apps/tauri/build-shim.mjs. Do not edit. */',
  },
})

console.log(`shim bundled -> ${outfile}`)
